version: '2.2'

volumes:
  mail_queue:

services:
  tor_proxy:
    # object 76f7fcaf094d28a2e8ffaf0a94c83f084c4fc03e
    # tag docker/4.1.0-tor0.4.4.8r0-amd64
    image: docker.io/fphammerle/tor-proxy@sha256:161a3d494032adb588b8e38bc11a568806ca1499e6085b08daaeb93245e51bc9
    cap_drop: [ALL]
    security_opt: [no-new-privileges]
    cpus: 0.5
    mem_limit: 128m
    restart: unless-stopped
  monitor:
    build: .
    image: fphammerle/onion-service-status-mail
    environment:
      TOR_HOST: tor_proxy
      TOR_PORT: 9050
      ONION_SERVICE_HOST: change-me.onion
      ONION_SERVICE_PORT: 80
      # TIMEOUT_SECONDS: 8
      # SLEEP_DURATION: 1m
      MAIL_TO: change.me@domain.tld, another@recipient.com
      #VERBOSE: 1
    volumes:
    - mail_queue:/var/spool/dma:rw
    cap_drop: [ALL]
    security_opt: [no-new-privileges]
    cpus: 0.2
    mem_limit: 64m
    restart: unless-stopped

# https://docs.docker.com/compose/compose-file/
