version: '2.2'

volumes:
  mail_queue:

services:
  tor_proxy:
    # 1.0.0-tor0.4.1.6-amd64
    image: fphammerle/tor-proxy@sha256:ad55d07b1b21c35fa044dc3e1ea6c7d8494f39eb89491ddad35c245340f7cd4b
    security_opt: ['no-new-privileges']
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 128m
  monitor:
    build: .
    image: fphammerle/onion-service-status-mail
    environment:
      TOR_HOST: tor_proxy
      TOR_PORT: 9050
      ONION_SERVICE_HOST: change-me.onion
      ONION_SERVICE_PORT: 80
      # TIMEOUT_SECONDS: 8
      # SLEEP_DURATION: 1m
      RECIPIENT_ADDRESS: change.me@domain.tld
      # VERBOSE: 1
    volumes:
    - mail_queue:/var/spool/dma:rw
    security_opt: [no-new-privileges]
    restart: unless-stopped
    cpus: 0.2
    mem_limit: 64m

# https://docs.docker.com/compose/compose-file/
